# Generated by Django 4.2.1 on 2023-05-29 17:16

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('receive', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('name', models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator])),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('admins', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='+', to='chat.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
